package com.vietsci.cms.frontend.etopup.dto;
// Generated Apr 22, 2014 4:43:38 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * StockAgentMapId generated by hbm2java
 */

public class StockAgentMapDTO extends BaseDTO implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -744334236900235642L;
  private Long stockId;
  private Long oldStockId;
  private Long agentId;
  private Date createDate;
  private Date endDate;
  private Integer status;
  private BigDecimal batchId;
  private Boolean delStatus = Boolean.FALSE;

  public Long getStockId() {
    return this.stockId;
  }

  public void setStockId(Long stockId) {
    this.stockId = stockId;
  }

  public Long getAgentId() {
    return this.agentId;
  }

  public void setAgentId(Long agentId) {
    this.agentId = agentId;
  }

  public Date getCreateDate() {
    return this.createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public Date getEndDate() {
    return this.endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public Integer getStatus() {
    return this.status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public BigDecimal getBatchId() {
    return this.batchId;
  }

  public void setBatchId(BigDecimal batchId) {
    this.batchId = batchId;
  }

  public boolean isDelStatus() {
    return delStatus;
  }

  public void setDelStatus(boolean delStatus) {
    this.delStatus = delStatus;
  }

  public Long getOldStockId() {
    return oldStockId;
  }

  public void setOldStockId(Long oldStockId) {
    this.oldStockId = oldStockId;
  }

}
