DROP TABLE "IVR_CMS"."CMS_USER";
CREATE TABLE "IVR_CMS"."CMS_USER" 
   ("USER_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	"ROLE" SMALLINT CONSTRAINT UNSIGNED NOT NULL ENABLE, 
	"MOBILE" VARCHAR2(15 BYTE) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	"LOGIN_COUNT" SMALLINT DEFAULT 0, 
	"ACTIVE_STATUS" VARCHAR2(1 BYTE), 
	"COMPANY_ID" NUMBER(6,0), 
    "CREATED_BY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"UPDATED_DATE" DATE NOT NULL ENABLE,
	PRIMARY KEY ("USER_ID")
   ); 
   
DROP SEQUENCE "IVR_CMS"."CMS_USER_SEQ";
CREATE SEQUENCE  "IVR_CMS"."CMS_USER_SEQ"  MINVALUE 1 
MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 NOORDER  NOCYCLE ;

DROP TABLE "IVR_CMS"."CMS_SERVICES";
CREATE TABLE "IVR_CMS"."CMS_SERVICES" 
   ("SERVICE_ID" NUMBER(6,0) NOT NULL ENABLE, 
    "SERVICE_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SERVICE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SERVICE_INFO" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"SHORT_CODE" VARCHAR2(8 BYTE) NOT NULL ENABLE, /*Đầu số (short code): ví dụ: 9768*/ 
	"REGISTER_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CANCEL_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ACTIVE_STATUS" VARCHAR2(1 BYTE), 
    "CREATED_BY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"UPDATED_DATE" DATE NOT NULL ENABLE,
	PRIMARY KEY ("SERVICE_ID")
   ); 
   
DROP SEQUENCE "IVR_CMS"."CMS_SERVICES_SEQ";
CREATE SEQUENCE  "IVR_CMS"."CMS_SERVICES_SEQ"  MINVALUE 1 
MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 100 NOORDER  NOCYCLE ;

DROP TABLE "IVR_CMS"."CMS_USER_SERVICE";
CREATE TABLE "IVR_CMS"."CMS_USER_SERVICE" 
   ("USER_ID" NUMBER(6,0) NOT NULL ENABLE, 
    "SERVICE_ID" NUMBER(6,0) NOT NULL ENABLE,
    PRIMARY KEY ("USER_ID", "SERVICE_ID"),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES CMS_USER (USER_ID),
	CONSTRAINT FK_SERVICE_ID FOREIGN KEY (SERVICE_ID) REFERENCES CMS_SERVICES (SERVICE_ID)
    );