package com.vietsci.cms.api.model;

// Generated Apr 14, 2016 11:37:53 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmsUser generated by hbm2java
 */
@Entity
@Table(name = "CMS_USER", schema="IVR_CMS")
public class CmsUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int userId;
	private String userName;
	private String password;
	private BigDecimal role;
	private String mobile;
	private String email;
	private BigDecimal loginCount;
	private String activeStatus;
	private String createdBy;
	private Date createdDate;

	public CmsUser() {
	}
	
	public CmsUser(String userName, String password,
			BigDecimal role, String mobile, String email, String createdBy,
			Date createdDate) {
		this.userName = userName;
		this.password = password;
		this.role = role;
		this.mobile = mobile;
		this.email = email;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public CmsUser(int userId, String userName, String password,
			BigDecimal role, String mobile, String email, String createdBy,
			Date createdDate) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.role = role;
		this.mobile = mobile;
		this.email = email;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}
	
	public CmsUser(String userName, String password,
			BigDecimal role, String mobile, String email,
			BigDecimal loginCount, String activeStatus, String createdBy,
			Date createdDate) {
		this.userName = userName;
		this.password = password;
		this.role = role;
		this.mobile = mobile;
		this.email = email;
		this.loginCount = loginCount;
		this.activeStatus = activeStatus;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public CmsUser(int userId, String userName, String password,
			BigDecimal role, String mobile, String email,
			BigDecimal loginCount, String activeStatus, String createdBy,
			Date createdDate) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.role = role;
		this.mobile = mobile;
		this.email = email;
		this.loginCount = loginCount;
		this.activeStatus = activeStatus;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	@Id
	@Column(name = "USER_ID", unique = true, nullable = false, precision = 6, scale = 0)
	@GeneratedValue(generator="cms_user_seq", strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="cms_user_seq", sequenceName="CMS_USER_SEQ")
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ROLE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRole() {
		return this.role;
	}

	public void setRole(BigDecimal role) {
		this.role = role;
	}

	@Column(name = "MOBILE", nullable = false, length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "LOGIN_COUNT", precision = 22, scale = 0)
	public BigDecimal getLoginCount() {
		return this.loginCount;
	}

	public void setLoginCount(BigDecimal loginCount) {
		this.loginCount = loginCount;
	}

	@Column(name = "ACTIVE_STATUS", length = 1)
	public String getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(String activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 20)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", nullable = false, length = 7)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
