package com.vietsci.cms.frontend.etopup.model;

/**
 * ApParamId generated by hbm2java
 */
public class ApParamId implements java.io.Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = -3566013188212357038L;
  private String parType;
  private String parName;

  public ApParamId() {
  }

  public ApParamId(String parType, String parName) {
    this.parType = parType;
    this.parName = parName;
  }

  public String getParType() {
    return this.parType;
  }

  public void setParType(String parType) {
    this.parType = parType;
  }

  public String getParName() {
    return this.parName;
  }

  public void setParName(String parName) {
    this.parName = parName;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ApParamId))
      return false;
    ApParamId castOther = (ApParamId) other;

    return ((this.getParType() == castOther.getParType()) || (this.getParType() != null
        && castOther.getParType() != null && this.getParType().equals(castOther.getParType())))
        && ((this.getParName() == castOther.getParName()) || (this.getParName() != null
            && castOther.getParName() != null && this.getParName().equals(castOther.getParName())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getParType() == null ? 0 : this.getParType().hashCode());
    result = 37 * result + (getParName() == null ? 0 : this.getParName().hashCode());
    return result;
  }

}