package com.vietsci.cms.frontend.etopup.model;
// Generated Apr 22, 2014 4:43:38 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * StockAgentMapId generated by hbm2java
 */
public class StockAgentMapId implements java.io.Serializable {
  /**
   * 
   */
  private static final long serialVersionUID = -2087936279683230041L;
  private Long stockId;
  private Long agentId;

  public StockAgentMapId() {
  }

  public StockAgentMapId(Long stockId, Long agentId) {
    this.stockId = stockId;
    this.agentId = agentId;
  }

  public void setAgentId(Long agentId) {
    this.agentId = agentId;
  }
  
  

  public Long getStockId() {
    return stockId;
  }

  public void setStockId(Long stockId) {
    this.stockId = stockId;
  }

  public Long getAgentId() {
    return agentId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof StockAgentMapId))
      return false;
    StockAgentMapId castOther = (StockAgentMapId) other;

    return ((this.getStockId() == castOther.getStockId()) || (this.getStockId() != null
        && castOther.getStockId() != null && this.getStockId().equals(castOther.getStockId())))
        && ((this.getAgentId() == castOther.getAgentId()) || (this.getAgentId() != null
            && castOther.getAgentId() != null && this.getAgentId().equals(castOther.getAgentId())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getStockId() == null ? 0 : this.getStockId().hashCode());
    result = 37 * result + (getAgentId() == null ? 0 : this.getAgentId().hashCode());
    return result;
  }
  
  public String toString(){
    return this.stockId.toString() + "|" + this.agentId.toString();
  }

  
}
