package com.vietsci.cms.frontend.etopup.model;
// Generated Apr 22, 2014 4:43:38 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import com.vietsci.cms.frontend.etopup.dto.StockAgentMapDTO;
/**
 * StockAgentMap generated by hbm2java
 */

public class StockAgentMap implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 8369876165608216478L;
  private StockAgentMapId id;
  private Date createDate;
  private Date endDate;
  private Integer status;
  private BigDecimal batchId;
  private Boolean delStatus;

  public StockAgentMap() {
  }
  
  public StockAgentMap(StockAgentMapDTO stockAgentMapDTO){
    StockAgentMapId samId = new StockAgentMapId(stockAgentMapDTO.getStockId(),stockAgentMapDTO.getAgentId());
    this.id = samId;
    this.createDate = stockAgentMapDTO.getCreateDate();
    this.endDate = stockAgentMapDTO.getEndDate();
    this.status = stockAgentMapDTO.getStatus();
    this.batchId = stockAgentMapDTO.getBatchId();
    this.delStatus = stockAgentMapDTO.isDelStatus();
  }

  public StockAgentMap(StockAgentMapId id, Date createDate, Integer status) {
    this.id = id;
    this.createDate = createDate;
    this.status = status;
  }

  public StockAgentMap(StockAgentMapId id, Date createDate, Date endDate, Integer status, BigDecimal batchId) {
    this.id = id;
    this.createDate = createDate;
    this.endDate = endDate;
    this.status = status;
    this.batchId = batchId;
  }

  public StockAgentMapId getId() {
    return id;
  }

  public void setId(StockAgentMapId id) {
    this.id = id;
  }

  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public Date getEndDate() {
    return endDate;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public BigDecimal getBatchId() {
    return batchId;
  }

  public void setBatchId(BigDecimal batchId) {
    this.batchId = batchId;
  }

  public boolean isDelStatus() {
    return delStatus;
  }

  public void setDelStatus(boolean delStatus) {
    this.delStatus = delStatus;
  }

  public static enum Status {
    INACTIVE(0, "Hết hiệu lực"),
    ACTIVE(1, "Hiệu lực");

    private int value;
    private String name;


    private Status(int value, String name) {
      this.value = value;
      this.name = name;
    }

    public int getValue() {
      return value;
    }

    public String getName() {
      return name;
    }
  }
}
