package com.vietsci.cms.frontend.etopup.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Trans generated by hbm2java
 */
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "idJson")
public class TransExt implements java.io.Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = -5401115879264697418L;
  
  private Long id;
  private Trans trans;
  private Date transDate;
  private String keyName;
  private String keyValue;
  
  public TransExt() {
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Trans getTrans() {
    return trans;
  }

  public void setTrans(Trans trans) {
    this.trans = trans;
  }

  public Date getTransDate() {
    return transDate;
  }

  public void setTransDate(Date transDate) {
    this.transDate = transDate;
  }

  public String getKeyName() {
    return keyName;
  }

  public void setKeyName(String keyName) {
    this.keyName = keyName;
  }

  public String getKeyValue() {
    return keyValue;
  }

  public void setKeyValue(String keyValue) {
    this.keyValue = keyValue;
  }

}
